import { createHash, randomBytes } from "node:crypto";
import { StorageError } from "./types";

/**
 * Storage keys are strictly validated: lowercase segments, no traversal, no
 * absolute paths, bounded length. Keys are generated by the server only.
 */
const SEGMENT = /^[a-z0-9][a-z0-9._-]{0,120}$/;
const MAX_KEY_LENGTH = 256;

export function isValidStorageKey(key: string): boolean {
  if (typeof key !== "string" || key.length === 0 || key.length > MAX_KEY_LENGTH) return false;
  if (key.startsWith("/") || key.includes("\\") || key.includes("//")) return false;
  const parts = key.split("/");
  if (parts.length < 2) return false;
  return parts.every((part) => SEGMENT.test(part) && part !== "." && part !== "..");
}

export function assertValidStorageKey(key: string): void {
  if (!isValidStorageKey(key)) {
    throw new StorageError("invalid_key", "Invalid storage key.");
  }
}

function safeSegment(value: string): string {
  const cleaned = value.toLowerCase().replace(/[^a-z0-9._-]/g, "");
  if (!cleaned || cleaned === "." || cleaned === "..") {
    throw new StorageError("invalid_key", "Invalid storage key segment.");
  }
  return cleaned.slice(0, 120);
}

/** `extensions/<user-id>/<random>.zip` */
export function packageStorageKey(userId: string): string {
  return `extensions/${safeSegment(userId)}/${randomBytes(16).toString("hex")}.zip`;
}

/** `artifacts/<run-id>/<random>.<ext>` */
export function artifactStorageKey(runId: string, extension: string): string {
  const ext = safeSegment(extension.replace(/^\./, ""));
  return `artifacts/${safeSegment(runId)}/${randomBytes(16).toString("hex")}.${ext}`;
}

export function sha256Hex(data: Uint8Array): string {
  return createHash("sha256").update(data).digest("hex");
}
