import "server-only";
import { getDb } from "@/lib/db/client";
import { deletePublicationRow, getPublicationBySlug, insertPublicationRow, listPublications } from "@/lib/organizations/repository";
import { getOrgReport } from "@/lib/db/repositories/reports";
import { recordAuditEvent } from "@/lib/audit/service";
import { AppError } from "@/lib/observability/errors";
import type { ReportRow } from "@/lib/db/schema/types";

/**
 * Public report publications (Phase 10).
 *
 * Published reports are served through a deliberately narrow projection:
 * scores, browser outcomes and provenance labels only. Organization identity,
 * member identities, source code, URLs, container ids and internal job data
 * never reach the public surface.
 */

const SLUG_PATTERN = /^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$/;

export interface PublicationView {
  id: string;
  slug: string;
  reportId: string;
  title: string;
  summary: string | null;
  createdAt: number;
}

function toView(row: { id: string; slug: string; report_id: string; title: string; summary: string | null; created_at: number }): PublicationView {
  return { id: row.id, slug: row.slug, reportId: row.report_id, title: row.title, summary: row.summary, createdAt: row.created_at };
}

export function listOrganizationPublications(organizationId: string): PublicationView[] {
  return (listPublications(organizationId) as unknown as Array<Record<string, unknown>>).map((row) =>
    toView({
      id: String(row.id),
      slug: String(row.slug),
      report_id: String(row.report_id),
      title: String(row.title ?? "Report"),
      summary: row.summary === null || row.summary === undefined ? null : String(row.summary),
      created_at: Number(row.created_at ?? 0),
    }),
  );
}

export function publishReport(ctx: { userId: string; organizationId: string }, input: { reportId: string; slug?: string | null; summary?: string | null }): PublicationView {
  const report = getOrgReport(ctx.organizationId, input.reportId);
  if (!report) throw new AppError("NOT_FOUND", { message: "Report not found." });
  const slug = (input.slug ?? "").trim().toLowerCase();
  if (!SLUG_PATTERN_PATTERN_CHECK(slug)) throw new AppError("INVALID_INPUT", { message: "Slugs are 3–64 chars: lowercase letters, digits and hyphens." });
  if (getPublicationBySlug(slug)) throw new AppError("CONFLICT", { message: "That slug is taken." });
  const summary = typeof input.summary === "string" ? input.summary.slice(0, 300) : report.summary;
  let row: Record<string, unknown>;
  try {
    row = insertPublicationRow({ organizationId: ctx.organizationId, reportId: report.id, slug, summary, createdBy: ctx.userId }) as unknown as Record<string, unknown>;
  } catch {
    throw new AppError("CONFLICT", { message: "That slug is taken." });
  }
  recordAuditEvent({ organizationId: ctx.organizationId, actorUserId: ctx.userId, action: "report.published", resourceType: "report", resourceId: report.id, metadata: { slug } });
  return toView({
    id: String(row.id),
    slug: String(row.slug),
    report_id: String(row.report_id),
    title: String(row.title ?? "Report"),
    summary: row.summary == null ? null : String(row.summary),
    created_at: Number(row.created_at ?? 0),
  });
}

function SLUG_PATTERN_PATTERN_CHECK(slug: string): boolean {
  return SLUG_PATTERN.test(slug);
}

export function unpublishReport(ctx: { userId: string; organizationId: string }, publicationId: string): void {
  const rows = listPublications(ctx.organizationId) as unknown as Array<{ id: string; report_id: string; slug: string }>;
  const row = rows.find((candidate) => candidate.id === publicationId);
  if (row && deletePublicationRow(ctx.organizationId, publicationId)) {
    recordAuditEvent({ organizationId: ctx.organizationId, actorUserId: ctx.userId, action: "report.unpublished", resourceType: "report", resourceId: row.report_id, metadata: { slug: row.slug } });
  }
}

export interface PublicReportProjection {
  slug: string;
  title: string;
  summary: string | null;
  scores: { health: number | null; runtime: number | null; overall: number | null };
  browsers: Array<{ browserId: string; status: string; executed: boolean; engine: string | null }>;
  compatibility: { score: number | null; coverage: number | null } | null;
  provenance: Array<{ label: string; meaning: string }>;
  generatedAt: number;
  schemaVersion: 1;
}

/** Provenance labels are fixed vocabulary — never derived from user input. */
export const PROVENANCE_LABELS = [
  { label: "Verified by ExtensionLab", meaning: "Measured directly by the ExtensionLab test infrastructure." },
  { label: "AI interpretation", meaning: "Generated by an AI model from extension metadata; not independently verified." },
  { label: "User provided", meaning: "Supplied by the publisher; not verified by ExtensionLab." },
  { label: "Infrastructure unavailable", meaning: "A measurement could not be collected; treated as unknown, never as passing." },
] as const;

export function getPublicReportBySlug(slug: string): PublicReportProjection | null {
  const publication = getPublicationBySlug(slug) as unknown as { id: string; slug: string; report_id: string; organization_id: string; title: string; summary: string | null; created_at: number } | null;
  if (!publication) return null;
  const report = getDb().prepare("SELECT * FROM reports WHERE id = ?").get(publication.report_id) as unknown as ReportRow | undefined;
  if (!report) return null;
  let browsers: PublicReportProjection["browsers"] = [];
  let compatibility: PublicReportProjection["compatibility"] = null;
  try {
    const parsed = JSON.parse(report.report_json) as { kind?: string; browsers?: Array<{ browserId?: string; status?: string; executed?: boolean; engine?: string | null }>; compatibility?: { score?: number | null; coverage?: number | null } };
    if (Array.isArray(parsed.browsers)) {
      browsers = parsed.browsers
        .filter((browser): browser is { browserId: string; status: string; executed: boolean; engine: string | null } => typeof browser.browserId === "string")
        .map((browser) => ({ browserId: browser.browserId, status: String(browser.status ?? "unknown"), executed: Boolean(browser.executed), engine: typeof browser.engine === "string" ? browser.engine : null }));
    }
    if (parsed.compatibility && typeof parsed.compatibility.score === "number") {
      compatibility = { score: parsed.compatibility.score, coverage: typeof parsed.compatibility.coverage === "number" ? parsed.compatibility.coverage : 0 };
    }
  } catch {
    // Fall through with empty browser details.
  }
  return {
    slug: publication.slug,
    title: report.title,
    summary: publication.summary ?? report.summary,
    scores: { health: report.health_score, runtime: report.runtime_score, overall: report.overall_score },
    browsers,
    compatibility,
    provenance: [...PROVENANCE_LABELS],
    generatedAt: report.created_at,
    schemaVersion: 1,
  };
}
